language: go

go: 1.6.3

dist: trusty

group: edge

env:
  global:
  - GO15VENDOREXPERIMENT='1'

addons:
  artifacts:
    paths:
    - "./build/linux/amd64/gcloud-cleanup"
    - "./build/darwin/amd64/gcloud-cleanup"
    - "./build.tar.gz"
    target_paths:
    - travis-ci/gcloud-cleanup/$TRAVIS_BRANCH
    - travis-ci/gcloud-cleanup/$TRAVIS_COMMIT

install:
- make prereqs

script:
- travis_retry make deps
- make crossbuild

after_script:
- tar -czvf build.tar.gz build Procfile Makefile
