language: go

go: 1.5.1

dist: trusty

group: edge

env:
  global:
  - GCLOUD_CLEANUP_ONCE=1
  - GCLOUD_READ_EXE="${TRAVIS_BUILD_DIR}/.cache/gcloud-read"
  - GCLOUD_WRITE_EXE='echo not really gcloud'
  - GO15VENDOREXPERIMENT='1'

install:
- go get github.com/FiloSottile/gvt
- go get github.com/laher/goxc

script:
- travis_retry make deps
- make crossbuild
